### ISSUE TITLE
Mojoportal  2.6.0  Scout Skin parse Error

### ISSUE THREAD

**Issue by joedavis01** [i7MEDIA/mojoskins#11]
I  am running mojoportal 2.6 on a local dev site. when I change the site skin to scout I get a parse error  on line 14 of the theme skin.  This issue doesn't show up using the framework skins. 

> Line 12:     These are for Pro Modules
Line 13:     ========================= --%>
Line 14:     <%@ Register TagPrefix="sts" Namespace="sts.Web.UI" Assembly="sts.Web.UI" %>
Line 15:     <%@ Register Namespace="sts.Events.Web.UI.Controls" Assembly="sts.Events.Web.UI" TagPrefix="ecp" %>
Line 16:     <%@ Register TagPrefix="fundr"  Namespace="sts.FundRaiser.Web.UI" Assembly="sts.FundRaiser.Web.UI" %>

**Comment by JosephMDavis** [comment]
Comment out the pro modules. Looks like we forgot to do that before committing the skin to the repo.

**Comment by Isaac-Hall** [comment]
I have fixed this in the repo now - you'll need to remove the comments lines if you do have Pro modules installed. Sorry about that!
