### ISSUE TITLE
Framework Skin: Missing Styles

### ISSUE THREAD

**Issue by joseph-fowler** [i7MEDIA/mojoskins#21]
Administration Menu >> Site List >> Site Settings >> Privacy Policy Url
Administration Menu >> Site List >> Site Settings >> Skin
Shared Files Content - Scrollbar 
Audio Player - Scrollbar
Video Player - Scrollbar
Google Translate - Scrollbar

**Comment by joseph-fowler** [comment]
Administration Menu / Content Style Templates / "Choose File" (very noticeable on bootswatch-darkly)

**Comment by Isaac-Hall** [comment]
Fixed with https://github.com/i7MEDIA/mojoskins/commit/1e00360bcefc8d9ca6867537aa338537e50eef3e

Except scrollbars, we're not adding custom scrollbars.
