### ISSUE TITLE
Business Blue: Administration Menu and other breaks

### ISSUE THREAD

**Issue by joseph-fowler** [i7MEDIA/mojoskins#25]
1. Seems to have old version of Administration Menu / Site Settings (no tabs, all config options on one page)
2. Footer has oddly place and non-functional log out icon (which does however function for login when logged out)
3. Administration Menu / Design Tools / Skin Management - Clicking on "view" on a skin opens that skin in the current tab, instead of a modal
4. Checkboxes are almost invisible without mouseover (see second page in Form Wizard on mtest)

**Comment by Isaac-Hall** [comment]
Fixed with https://github.com/i7MEDIA/mojoskins/commit/37346b1810402ba325fd6d585d6a9ff8fd7400ee
