### ISSUE TITLE
Bootswatch Superhero: Site Settings - Readability

### ISSUE THREAD

**Issue by joseph-fowler** [i7MEDIA/mojoskins#26]
Administration Menu / Site List / Site Settings - dark font on dark background makes it hard to read

**Comment by Isaac-Hall** [comment]
SuperHero was not loading the bootswatch colors correctly. Fixed with https://github.com/i7MEDIA/mojoskins/commit/fd8f47daf59992e5a4f24567cfaec02caeee8570
