### ISSUE TITLE
Bootswatch Darkly: Broken Input Dates and Form Wizard

### ISSUE THREAD

**Issue by joseph-fowler** [i7MEDIA/mojoskins#27]
1. Administration Menu / Advanced Tools / Index Browser - Filter by date inputs broken
2. Form Wizard / Administration / Submission Data - "View Submissions Grid" and "Browse Submissions", white text on white background

**Comment by Isaac-Hall** [comment]
Fixed with https://github.com/i7MEDIA/mojoskins/commit/1cbd2b29eb69a0f75bf01f85812455a03a913c93
